"""Cavalry renderer plugin, running as a project handoff.

Cavalry removed its CLI in 2.7; headless rendering is an Enterprise feature.
So this plugin cannot claim a finished file. What it can do reliably is build a
Cavalry JavaScript scene-builder script that lays out the shots, beat markers
and kinetic type from our pipeline data, plus a render-queue entry. The user
runs it from Cavalry's script editor and renders there.

Emitting `prepared` instead of `completed` keeps the GUI honest: it never shows
a fake percentage for work Cavalry has not done.
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

from .base import Capability, Emit, PluginInfo, RenderRequest

SEARCH_PATHS = (
    os.path.expandvars(r"%LOCALAPPDATA%\Programs\Cavalry\Cavalry.exe"),
    r"C:\Program Files\Cavalry\Cavalry.exe",
)

SCRIPT_DIR = Path(os.path.expandvars(r"%APPDATA%\Cavalry\Third-Party\Plugins"))


def find_cavalry() -> str | None:
    direct = shutil.which("Cavalry")
    if direct:
        return direct
    for candidate in SEARCH_PATHS:
        if Path(candidate).exists():
            return candidate
    return None


def _build_script(request: RenderRequest, payload_path: Path) -> str:
    """Cavalry scene-builder script.

    Uses only functions present in Cavalry's own
    `assets/MetaData/api_function_metadata.json`: createComp, setActiveComp,
    set, loadAsset, addAssetToComp, create, setInFrame, setOutFrame,
    createTimeMarker, addRenderQueueItem, readFromFile.
    """
    comp_name = request.output.stem
    return f"""// Generated by Modal GUI. Open in Cavalry's Script Editor and run.
// Source data: {payload_path.as_posix()}

(function () {{
  const fps = {request.fps};
  const payloadPath = {json.dumps(payload_path.as_posix())};
  const raw = api.readFromFile(payloadPath);
  if (!raw) {{
    console.log("Modal GUI: payload를 읽지 못했습니다: " + payloadPath);
    return;
  }}
  const data = JSON.parse(raw);
  const toFrames = function (seconds) {{ return Math.round(seconds * fps); }};

  const comp = api.createComp({json.dumps(comp_name)});
  api.setActiveComp(comp);
  api.set(comp, {{
    "resolution": [{request.width}, {request.height}],
    "fps": fps,
    "backgroundColor": "#000000"
  }});

  // Footage layers, one per shot, trimmed to the beat-snapped durations.
  let cursor = 0;
  data.shot_durations.forEach(function (seconds, index) {{
    const clipPath = data.clips[index % data.clips.length];
    const asset = api.loadAsset(clipPath, false);
    if (!asset) {{
      console.log("Modal GUI: 클립을 불러오지 못했습니다: " + clipPath);
      return;
    }}
    const layers = api.addAssetToComp(asset);
    const layer = Array.isArray(layers) ? layers[0] : layers;
    const length = toFrames(seconds);
    api.setInFrame(layer, cursor);
    api.setOutFrame(layer, cursor + length);
    cursor += length;
  }});

  // Kinetic type. Timing already matches the audio; add expressions in Cavalry
  // for the motion itself.
  data.cues.forEach(function (cue, index) {{
    const text = api.create("textShape", "cue_" + (index + 1));
    api.set(text, {{
      "text": cue.text,
      "fontSize": cue.size,
      "font.style": "Bold",
      "autoWidth": true,
      "autoHeight": true,
      "material.materialColor": "#ffffff",
      "horizontalAlignment": 1,
      "verticalAlignment": 1,
      "position.y": {request.height} * 0.34
    }});
    api.setInFrame(text, toFrames(cue.start));
    api.setOutFrame(text, toFrames(cue.end));
  }});

  const audioAsset = api.loadAsset(data.audio, false);
  if (audioAsset) {{
    api.addAssetToComp(audioAsset);
  }}

  // Beat markers so transitions and effects can be snapped by hand or script.
  data.beats.forEach(function (beat) {{
    api.createTimeMarker(toFrames(beat));
  }});

  api.addRenderQueueItem(comp);

  console.log("Modal GUI: " + data.shot_durations.length + "개 샷, " +
              data.cues.length + "개 타이포, " + data.beats.length +
              "개 비트 마커를 만들었습니다. Render Queue에서 출력 경로를 지정하고 렌더하세요.");
}})();
"""


class CavalryRenderer:
    id = "cavalry"
    name = "Cavalry"
    execution = "project_handoff"

    def describe(self) -> PluginInfo:
        executable = find_cavalry()
        return PluginInfo(
            id=self.id,
            name=self.name,
            execution="project_handoff",
            available=bool(executable),
            executable=executable,
            version=None,
            unavailable_reason=None if executable else "Cavalry가 설치되지 않았습니다.",
            capabilities=Capability(
                kinetic_typography=True,
                beat_reactive_cuts=True,
                beat_reactive_effects=True,
                audio_mux=True,
                expressions=True,
                max_resolution=None,
                watermark=False,
            ),
            notes=(
                "2.7에서 CLI가 제거되어 무인 렌더가 안 됩니다. 씬 구성 스크립트와 "
                "Render Queue 항목까지 만들어 두고, 실제 출력은 Cavalry에서 실행합니다. "
                "무료 티어는 Canva 계정 로그인이 필요하고 해상도 제한과 워터마크는 없습니다."
            ),
        )

    def render(self, request: RenderRequest, emit: Emit) -> Path:
        executable = find_cavalry()
        if not executable:
            emit("failed", message="Cavalry가 설치되지 않았습니다.")
            raise SystemExit(3)

        stem = request.output.stem
        payload_path = request.output.with_name(f"{stem}-cavalry-payload.json")
        script_path = request.output.with_name(f"{stem}-cavalry-build.js")
        payload_path.parent.mkdir(parents=True, exist_ok=True)

        emit("prepare_started", output=str(script_path), shots=len(request.shot_durations))
        payload_path.write_text(json.dumps({
            "clips": [str(path).replace("\\", "/") for path in request.clips],
            "audio": str(request.audio).replace("\\", "/"),
            "shot_durations": request.shot_durations,
            "beats": request.beats,
            "cues": [
                {"start": cue.start, "end": cue.end, "text": cue.text, "size": cue.size}
                for cue in request.cues
            ],
        }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        script_path.write_text(_build_script(request, payload_path), encoding="utf-8")

        installed_script = None
        if SCRIPT_DIR.exists():
            installed_script = SCRIPT_DIR / script_path.name
            installed_script.write_text(script_path.read_text(encoding="utf-8"), encoding="utf-8")

        emit(
            "prepared",
            script=str(script_path),
            payload=str(payload_path),
            installed_script=str(installed_script) if installed_script else None,
            executable=executable,
            message=(
                "Cavalry 씬 스크립트를 만들었습니다. Cavalry를 열고 Script Editor에서 "
                "이 스크립트를 실행한 뒤 Render Queue에서 출력하세요."
            ),
        )
        return script_path
